VERDICT_MAP = {
    "Waiting": 0,
    "Accepted": 1,
    "Wrong Answer": 2,
    "Time Limit Exceeded": 3,
    "Memory Limit Exceeded": 4,
    "Output Limit Exceeded": 5,
    "Runtime Error": 6,
    "Compile Error": 7,
    "System Error": 8,
    "Cancelled": 9,
    "Unknown Error": 10,
    "Hacked": 11,
    "Running": 20,
    "Compiling": 21,
    "Fetched": 22,
    "Ignored": 30,
    "Format Error": 31,
    "Hack Successful": 32,
    "Hack Unsuccessful": 33,
}

STATUS_VERDICT = {
    0: "Waiting",
    1: "Accepted",
    2: "Wrong Answer",
    3: "Time Limit Exceeded",
    4: "Memory Limit Exceeded",
    5: "Output Limit Exceeded",
    6: "Runtime Error",
    7: "Compile Error",
    8: "System Error",
    9: "Cancelled",
    10: "Unknown Error",
    11: "Hacked",
    20: "Running",
    21: "Compiling",
    22: "Fetched",
    30: "Ignored",
    31: "Format Error",
    32: "Hack Successful",
    33: "Hack Unsuccessful",
}
