VERDICT_MAP = {
    "Waiting": 0,
    "Accepted": 1,
    "Wrong Answer": 2,
    "Time Limit Exceeded": 3,
    "Memory Limit Exceeded": 4,
    "Output Limit Exceeded": 5,
    "Runtime Error": 6,
    "Compile Error": 7,
    "System Error": 8,
    "Canceled": 9,
    "Unknown Error": 10,
    "Hacked": 11,
    "Running": 12,
    "Compiling": 13,
    "Format Error": 31,
}

STATUS_VERDICT = {
    0: "Waiting",
    1: "Accepted",
    2: "Wrong Answer",
    3: "Time Limit Exceeded",
    4: "Memory Limit Exceeded",
    5: "Output Limit Exceeded",
    6: "Runtime Error",
    7: "Compile Error",
    8: "System Error",
    9: "Canceled",
    10: "Unknown Error",
    11: "Hacked",
    12: "Running",
    13: "Compiling",
    31: "Format Error",
}
